// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwL0Qjuvrj1bXPRyJsdfDW-j6Z5cBbZBQ',
    appId: '1:222107780521:android:7c9a40dffa2359358270b8',
    messagingSenderId: '222107780521',
    projectId: 'personalshopper-c98f1',
    storageBucket: 'personalshopper-c98f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFc6PMLIQ5tZ6oOlkrntzXOGxqy1syvcU',
    appId: '1:222107780521:ios:ef4424d19ce62a8d8270b8',
    messagingSenderId: '222107780521',
    projectId: 'personalshopper-c98f1',
    storageBucket: 'personalshopper-c98f1.appspot.com',
    iosBundleId: 'com.example.applicationPurchasingPlannerAndManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFc6PMLIQ5tZ6oOlkrntzXOGxqy1syvcU',
    appId: '1:222107780521:ios:ef4424d19ce62a8d8270b8',
    messagingSenderId: '222107780521',
    projectId: 'personalshopper-c98f1',
    storageBucket: 'personalshopper-c98f1.appspot.com',
    iosBundleId: 'com.example.applicationPurchasingPlannerAndManager',
  );
}
